# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65e68a0e431dd376b7d9bacc1d64a707ca2f3f09b4f31b718cbc93cc7848ca53645571ffb30e2f050e92594285122b81170553165ca3f246532fad623c2f9337

test:
  secret_key_base: 2cdb6e6d22508fbe2a6279d05d6e59dd188cb2c7ac163fc95c8e35ea17eae148db991b8fec41d35aa4e407efd7f692d86f9c80d87f5c9028f729dce94089feee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
